#!/usr/bin/env bash
# Publishes the marketplace to a dist branch (default: `plugins`) that holds
# only what consumers install: the manifests, the listed skill folders, and the
# top-level docs. Everything is taken from HEAD via `git archive`, so untracked
# or ignored files never ship. The dist branch keeps a linear history (one
# commit per source commit that changes it), so marketplace caches can fast-forward.
#
# Usage: ./scripts/publish-marketplace.sh [remote] [branch]
#   PUBLISH_DRY_RUN=1  build and commit locally, but do not push
# Requires: git, jq, and the Claude Code CLI (override the binary with $CLAUDE).
set -euo pipefail

REMOTE="${1:-origin}"
BRANCH="${2:-plugins}"
CLAUDE="${CLAUDE:-claude}"

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
MANIFEST=".claude-plugin/marketplace.json"

./scripts/check-plugin-marketplace.sh

SOURCE_SHA="$(git rev-parse HEAD)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
DIST="$WORK/dist"
mkdir -p "$DIST"

# Paths to ship: manifests, every listed skill folder, and the docs README links to.
mapfile -t skills < <(jq -r '.plugins[] | (.source | sub("/+$"; "")) as $src | (.skills // [])[]
  | ($src + "/" + sub("^\\./"; "") | sub("^\\./"; "") | sub("/+$"; ""))' "$MANIFEST" | sort -u)
paths=(.claude-plugin .github/plugin README.md "${skills[@]}")
for doc in SKILL_CREATION_GUIDE.md SKILL_BUILDER_SUBAGENT.md; do
  [[ -f "$doc" ]] && paths+=("$doc")
done

git archive --format=tar HEAD -- "${paths[@]}" | tar -x -C "$DIST"

echo "Validating built marketplace…"
$CLAUDE plugin validate "$DIST"
./scripts/smoke-test-plugins.sh "$DIST"

# Check out the existing dist branch (or start an orphan one) and replace its tree.
PUB="$WORK/publish"
git init -q "$PUB"
git -C "$PUB" remote add origin "$(git remote get-url "$REMOTE")"
if git -C "$PUB" fetch -q --depth 1 origin "refs/heads/$BRANCH" 2>/dev/null; then
  git -C "$PUB" checkout -q -b "$BRANCH" FETCH_HEAD
else
  echo "Branch $BRANCH does not exist on $REMOTE yet; creating it."
  git -C "$PUB" checkout -q --orphan "$BRANCH"
fi
git -C "$PUB" config user.name "$(git config user.name || echo 'github-actions[bot]')"
git -C "$PUB" config user.email "$(git config user.email || echo '41898282+github-actions[bot]@users.noreply.github.com')"

find "$PUB" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
cp -a "$DIST/." "$PUB/"
git -C "$PUB" add -A

if git -C "$PUB" rev-parse -q --verify HEAD >/dev/null && git -C "$PUB" diff --cached --quiet; then
  echo "Branch $BRANCH is already up to date with $SOURCE_SHA."
  exit 0
fi

git -C "$PUB" commit -q -m "Publish plugin marketplace from ${SOURCE_SHA:0:7}" \
  -m "Generated by scripts/publish-marketplace.sh from $SOURCE_SHA."

if [[ -n "${PUBLISH_DRY_RUN:-}" ]]; then
  echo "Dry run: built $BRANCH at $(git -C "$PUB" rev-parse --short HEAD), not pushing."
  git -C "$PUB" show --stat --oneline HEAD | head -40
  exit 0
fi

# Push with the caller's credentials (actions/checkout persists them for origin).
git -C "$PUB" config --local --unset-all http.https://github.com/.extraheader 2>/dev/null || true
if header="$(git -C "$ROOT" config --get "http.https://github.com/.extraheader")"; then
  git -C "$PUB" config --local http.https://github.com/.extraheader "$header"
fi
git -C "$PUB" push origin "HEAD:refs/heads/$BRANCH"
echo "Published $BRANCH at $(git -C "$PUB" rev-parse --short HEAD)."
